# -*- coding: utf-8 -*-

__author__ = 'Wang Chao'
__date__ = '14-11-26'

import os
import datetime

import flatprotocol


HEADER = """{comment} Generated By flatprotocol {version}
{comment} Generated At {now}
"""

FOOTER = """
"""


class BaseTemplate(object):
    FILE_EXTENSION = None
    FILE_COMMENT_SYMBOL = None

    def __init__(self, destination, module):
        self.module = module
        filename = module.spec.filename
        file_path = os.path.join(destination, '{0}{1}'.format(filename, self.FILE_EXTENSION))
        self.f = open(file_path, 'a')

    def make_file_header(self):
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return HEADER.format(
                comment=self.FILE_COMMENT_SYMBOL,
                version=flatprotocol.VERSION,
                now=now
                )

    def make_file_footer(self):
        return FOOTER

    def make_protocols(self):
        protocols = self.module.spec.protocols

        result = []
        for p in protocols:
            res = self.make_one_protocol(p)
            result.append(res)

        return '\n'.join(result)


    def make_one_protocol(self, p):
        raise NotImplementedError()


    def make(self):
        self.f.write(self.make_file_header())
        self.f.write(self.make_protocols())
        self.f.write(self.make_file_footer())

        self.f.close()


